import { Knex } from "knex";

import { ETableNames } from "../ETableNames";

export const seed = async (knex: Knex) => {
  const [{ count }] = await knex(ETableNames.position).count<
    [{ count: number }]
  >("* as count");
  if (!Number.isInteger(count) || Number(count) > 0) return;

  const positionsToInsert = positionSeed.map((positionName) => ({
    name: positionName,
  }));
  await knex(ETableNames.position).insert(positionsToInsert);
};

const positionSeed = [
  "Analista de Marketing",
  "Desenvolvedor Web",
  "Gerente de Recursos Humanos",
  "Assistente Administrativo",
  "Engenheiro de Software",
  "Analista Financeiro",
  "Designer Gráfico",
  "Coordenador de Vendas",
  "Especialista em SEO",
  "Analista de Suporte Técnico",
  "Consultor de Vendas",
  "Analista de Qualidade",
  "Supervisor de Produção",
  "Gerente de Projetos",
  "Assistente de RH",
  "Assistente de Marketing",
  "Analista de Compras",
  "Assistente Financeiro",
  "Analista de Sistemas",
  "Engenheiro Civil",
  "Analista de Negócios",
  "Estagiário de Marketing",
  "Recepcionista",
  "Operador de Caixa",
  "Técnico em Informática",
  "Analista de Logística",
  "Supervisor de Qualidade",
  "Técnico em Segurança do Trabalho",
  "Analista de RH",
  "Designer de Interiores",
  "Coordenador de Produção",
  "Especialista em Marketing Digital",
  "Analista de PCP",
  "Analista Contábil",
  "Técnico em Eletrônica",
  "Assistente de Compras",
  "Analista de Suporte",
  "Analista de BI",
  "Assistente Administrativo Financeiro",
  "Gerente Comercial",
  "Analista de Customer Success",
  "Auxiliar de Escritório",
  "Engenheiro Eletricista",
  "Técnico em Mecânica",
  "Estagiário de RH",
  "Assistente de Vendas",
  "Coordenador de Logística",
  "Analista de Marketing Digital",
  // Continuação dos cargos...
  "Gerente de Operações",
  "Analista de Planejamento Financeiro",
  "Coordenador de Recursos Humanos",
  "Assistente de Comunicação",
  "Desenvolvedor Mobile",
  "Analista de Comércio Exterior",
  "Analista de Segurança da Informação",
  "Gerente de Logística",
  "Especialista em Recrutamento e Seleção",
  "Analista de Controladoria",
  "Engenheiro de Produção",
  "Assistente Administrativo de Vendas",
  "Analista de Marketing Digital Sênior",
  "Supervisor de Produção Industrial",
  "Analista de Relações Públicas",
  "Coordenador de Qualidade",
  "Analista de Garantia da Qualidade",
  "Especialista em Treinamento e Desenvolvimento",
  "Analista de Tesouraria",
  "Assistente de Departamento Pessoal",
  "Coordenador de TI",
  "Analista de Suporte Técnico Nível II",
  "Analista de Atendimento ao Cliente",
  "Gerente de Projetos de TI",
  "Especialista em Mídias Sociais",
  "Assistente de Marketing Digital",
  "Engenheiro de Manutenção",
  "Analista de Planejamento Estratégico",
  "Gerente de Operações de Vendas",
  "Coordenador de Produção Industrial",
  "Especialista em Compras",
  "Analista de Sistemas ERP",
  "Assistente de Recursos Humanos",
  "Analista de Marketing de Conteúdo",
  "Coordenador de Facilities",
  "Gerente de Vendas Internacionais",
  "Especialista em Inteligência de Mercado",
  "Analista de Custos",
  "Assistente Administrativo Financeiro Pleno",
  "Coordenador de Operações",
  "Analista de Qualidade de Software",
  "Gerente de Marketing",
  "Especialista em Relações Trabalhistas",
  "Analista de Trade Marketing",
  "Supervisor de RH",
  "Assistente de Suprimentos",
  "Analista de BI e Big Data",
  "Coordenador de Planejamento Financeiro",
  "Especialista em Gestão de Pessoas",
  "Analista de Infraestrutura de TI",
  "Assistente de Compras Internacionais",
  "Gerente de Desenvolvimento de Negócios",
  "Analista de Comunicação Interna",
  "Coordenador de Engenharia de Produto",
  "Especialista em SEO e SEM",
  "Analista de Pricing",
  "Assistente de Planejamento Financeiro",
  "Gerente de Compras",
  "Especialista em Recursos Humanos",
  "Analista de Marketing de Performance",
  "Coordenador de Projetos de TI",
  "Especialista em Marketing de Produto",
  "Analista de Comércio Eletrônico",
  "Assistente de Logística",
  "Gerente de Operações de Logística",
  "Analista de Gestão de Frota",
  "Coordenador de Controladoria",
  "Especialista em Desenvolvimento Organizacional",
  "Analista de Sistemas Pleno",
  "Assistente Administrativo de Compras",
  "Gerente de Planejamento Estratégico",
  "Analista de Business Intelligence",
  "Coordenador de Vendas Externas",
  "Especialista em CRM",
  "Analista de Mídias Sociais",
  "Assistente de Relações Trabalhistas",
  "Gerente de Operações de TI",
  "Analista de Comunicação Digital",
  "Coordenador de Recrutamento e Seleção",
  "Especialista em Planejamento de Demanda",
  "Analista de Tesouraria Sênior",
  "Assistente de Marketing de Produto",
  "Gerente de Inteligência de Mercado",
  "Especialista em Desenvolvimento de Negócios",
  "Analista de Suporte Técnico Nível III",
  "Coordenador de Relacionamento com o Cliente",
  "Especialista em Marketing Promocional",
  "Analista de Negócios Digitais",
  "Assistente de Qualidade",
  "Gerente de Operações de Produção",
  "Analista de Segurança Patrimonial",
  "Coordenador de Marketing Digital",
  "Especialista em Planejamento Tributário",
  "Analista de Logística Internacional",
  "Assistente Administrativo de RH",
  "Gerente de Desenvolvimento de Produto",
  "Analista de Trade Marketing Pleno",
  "Coordenador de Análise de Dados",
  "Especialista em Comunicação Empresarial",
  "Analista de Gestão de Projetos",
  "Assistente de Customer Success",
  "Gerente de Vendas Internas",
  "Analista de SEO",
  "Coordenador de Produção de Eventos",
  "Especialista em Recrutamento e Seleção",
  "Analista de Gestão de Processos",
  "Assistente de Inteligência de Mercado",
  "Gerente de Operações de Vendas",
  "Analista de Negócios Pleno",
  "Coordenador de Relações Trabalhistas",
  "Especialista em Supply Chain",
  "Analista de Infraestrutura de Redes",
  "Assistente de Trade Marketing",
  "Gerente de Planejamento de Produção",
  "Analista de Marketing Digital Pleno",
  "Coordenador de Projetos de Engenharia",
  "Especialista em Pesquisa de Mercado",
  "Analista de Contas a Receber",
  "Assistente de Business Intelligence",
  "Gerente de Expansão de Mercado",
  "Analista de Logística Reversa",
  "Coordenador de Relações com Investidores",
  "Especialista em Gestão de Performance",
  "Analista de Mídia Digital",
  "Assistente de Planejamento de Demanda",
  "Gerente de Operações de Logística Internacional",
  "Analista de Inteligência de Mercado",
  "Coordenador de Comunicação Interna",
  "Especialista em Planejamento Estratégico",
  "Analista de Compras Internacionais",
  "Assistente de CRM",
  "Gerente de Engenharia de Produto",
  "Analista de Marketing de Conteúdo Sênior",
  "Coordenador de Desenvolvimento Organizacional",
  "Especialista em Gestão de Qualidade",
  "Analista de Controladoria Pleno",
  "Assistente de Logística Internacional",
  "Gerente de Operações de Produção Industrial",
  "Analista de Sistemas Júnior",
  "Coordenador de Segurança da Informação",
  "Especialista em Desenvolvimento de Produto",
  "Analista de Relacionamento com o Cliente",
  "Assistente de Planejamento Tributário",
  "Gerente de Marketing Digital",
  "Analista de Recursos Humanos Pleno",
  "Coordenador de Supply Chain",
  "Especialista em Análise de Dados",
  "Analista de Marketing de Performance Sênior",
  "Assistente de Inteligência de Mercado",
  "Gerente de Operações de Vendas Internas",
  "Analista de Negócios Digitais Pleno",
  "Coordenador de E-commerce",
  "Especialista em Gestão de Projetos",
  "Analista de Trade Marketing Sênior",
  "Assistente de Supply Chain",
  "Gerente de Desenvolvimento de Negócios",
  "Analista de Mídias Sociais Sênior",
  "Coordenador de Atendimento ao Cliente",
  "Especialista em Relações Trabalhistas",
  "Analista de Logística de Distribuição",
  "Assistente de Marketing de Produto",
  "Gerente de Operações de Produção Industrial",
  "Analista de Suporte Técnico Nível IV",
  "Coordenador de Análise de Crédito",
  "Especialista em Comunicação Digital",
  "Analista de Trade Marketing Júnior",
  "Assistente de Planejamento de Produção",
  "Gerente de Expansão de Mercado Internacional",
  "Analista de SEO e SEM",
  "Coordenador de Controladoria",
  "Especialista em Gestão de Custos",
  "Analista de Marketing de Conteúdo Pleno",
  "Assistente de Planejamento Estratégico",
  "Gerente de Engajamento de Clientes",
  "Analista de Logística de Armazenagem",
  "Coordenador de Pesquisa de Mercado",
  "Especialista em Gestão de Fornecedores",
  "Analista de Controladoria Sênior",
  "Assistente de Marketing de Conteúdo",
  "Gerente de Operações de Logística Reversa",
  "Analista de Sistemas Sênior",
  "Coordenador de Qualidade de Software",
  "Especialista em Gestão de Riscos",
  "Analista de Trade Marketing Pleno",
  "Assistente de Relações com Investidores",
  "Gerente de E-commerce",
  "Analista de Desenvolvimento Organizacional",
  "Coordenador de Planejamento de Demanda",
  "Especialista em Planejamento de Vendas",
  "Analista de CRM",
  "Assistente de Gestão de Pessoas",
  "Gerente de Engenharia de Processos",
  "Analista de Marketing de Conteúdo Júnior",
  "Coordenador de Desenvolvimento de Produto",
  "Especialista em Gestão de Projetos de TI",
  "Analista de Logística Internacional",
  "Assistente de Gestão de Fornecedores",
  "Gerente de Relações Trabalhistas",
  "Analista de Marketing Digital Sênior",
  "Coordenador de Operações de Produção Industrial",
  "Especialista em Engajamento de Clientes",
  "Analista de Gestão de Performance Sênior",
  "Assistente de Logística de Distribuição",
  "Gerente de Análise de Dados",
  "Analista de Trade Marketing Sênior",
  "Coordenador de Comunicação Digital",
  "Especialista em Gestão de Inventário",
  "Analista de SEO e SEM",
  "Assistente de Controladoria",
  "Gerente de Pesquisa de Mercado",
  "Analista de E-commerce",
  "Coordenador de Planejamento Tributário",
  "Especialista em Gestão de Transportes",
  "Analista de Marketing Digital Pleno",
  "Assistente de Desenvolvimento de Produto",
  "Gerente de Inteligência de Negócios",
  "Analista de Relações Trabalhistas",
  "Coordenador de Logística de Armazenagem",
  "Especialista em Gestão de Processos",
  "Analista de Controladoria Pleno",
  "Assistente de CRM",
  "Gerente de Desenvolvimento de Negócios Internacionais",
  "Analista de Logística de Transportes",
  "Coordenador de Análise de Crédito",
  "Especialista em Pesquisa de Mercado",
  "Analista de Marketing de Performance Pleno",
  "Assistente de Planejamento de Vendas",
  "Gerente de Relações com o Cliente",
  "Analista de Trade Marketing Pleno",
  "Coordenador de Operações de Logística de Distribuição",
  "Especialista em Planejamento Estratégico",
  "Analista de SEO e SEM Sênior",
  "Assistente de Gestão de Riscos",
  "Gerente de Desenvolvimento de Produto",
  "Analista de Marketing de Conteúdo Pleno",
  "Coordenador de Desenvolvimento de Negócios",
  "Especialista em Engajamento de Clientes",
  "Analista de Gestão de Performance Sênior",
  "Assistente de Logística Internacional",
  "Gerente de Marketing Digital",
  "Analista de CRM",
  "Coordenador de Planejamento de Demanda",
  "Especialista em Gestão de Projetos de TI",
  "Analista de Logística Internacional",
  "Assistente de Gestão de Fornecedores",
  "Gerente de Relações Trabalhistas",
  "Analista de Marketing Digital Sênior",
  "Coordenador de Operações de Produção Industrial",
  "Especialista em Engajamento de Clientes",
  "Analista de Gestão de Performance Sênior",
  "Assistente de Logística de Distribuição",
  "Gerente de Análise de Dados",
  "Analista de Trade Marketing Sênior",
  "Coordenador de Comunicação Digital",
  "Especialista em Gestão de Inventário",
  "Analista de SEO e SEM",
  "Assistente de Controladoria",
  "Gerente de Pesquisa de Mercado",
  "Analista de E-commerce",
  "Coordenador de Planejamento Tributário",
  "Especialista em Gestão de Transportes",
  "Analista de Marketing Digital Pleno",
  "Assistente de Desenvolvimento de Produto",
  "Gerente de Inteligência de Negócios",
  "Analista de Relações Trabalhistas",
  "Coordenador de Logística de Armazenagem",
  "Especialista em Gestão de Processos",
  "Analista de Controladoria Pleno",
  "Assistente de CRM",
  "Gerente de Desenvolvimento de Negócios Internacionais",
  "Analista de Logística de Transportes",
  "Coordenador de Análise de Crédito",
  "Especialista em Pesquisa de Mercado",
  "Analista de Marketing de Performance Pleno",
  "Assistente de Planejamento de Vendas",
  "Gerente de Relações com o Cliente",
  "Analista de Trade Marketing Pleno",
  "Coordenador de Operações de Logística de Distribuição",
  "Especialista em Planejamento Estratégico",
];
